# Catppuccin theme — pastel accent mapping inspired by catppuccin/tmux
THM_ROLE_SESSION="$THM_MAGENTA"
THM_ROLE_DIRECTORY="$THM_BLUE"
THM_ROLE_SSH="$THM_ORANGE"
THM_ROLE_APP="$THM_GREEN"
THM_ROLE_DATETIME="$THM_GRAY"
THM_ROLE_BATTERY="$THM_YELLOW"
THM_ROLE_WEATHER="$THM_CYAN"

THM_ROLE_SESSION_FG="$THM_BG_BASE"
THM_ROLE_MODULE_FG="$THM_BG_BASE"

THM_ROLE_ACTIVE_BG="$THM_MAGENTA"
THM_ROLE_ACTIVE_FG="$THM_BG_BASE"
THM_ROLE_INACTIVE_BG="$THM_BG_SURFACE"
THM_ROLE_INACTIVE_FG="$THM_FG_TEXT"
