# Cool theme — blue/cyan-shifted accent mapping
THM_ROLE_SESSION="$THM_CYAN"
THM_ROLE_DIRECTORY="$THM_BLUE"
THM_ROLE_SSH="$THM_MAGENTA"
THM_ROLE_APP="$THM_CYAN"
THM_ROLE_DATETIME="$THM_GRAY"
THM_ROLE_BATTERY="$THM_BLUE"
THM_ROLE_WEATHER="$THM_CYAN"

THM_ROLE_SESSION_FG="$THM_BG_BASE"
THM_ROLE_MODULE_FG="$THM_BG_BASE"

THM_ROLE_ACTIVE_BG="$THM_CYAN"
THM_ROLE_ACTIVE_FG="$THM_BG_BASE"
THM_ROLE_INACTIVE_BG="$THM_BG_SURFACE"
THM_ROLE_INACTIVE_FG="$THM_FG_TEXT"
