# Hacker theme — green-on-dark terminal aesthetic
THM_ROLE_SESSION="$THM_GREEN"
THM_ROLE_DIRECTORY="$THM_GREEN"
THM_ROLE_SSH="$THM_GREEN"
THM_ROLE_APP="$THM_GREEN"
THM_ROLE_DATETIME="$THM_GREEN"
THM_ROLE_BATTERY="$THM_GREEN"
THM_ROLE_WEATHER="$THM_GREEN"

THM_ROLE_SESSION_FG="$THM_BG_BASE"
THM_ROLE_MODULE_FG="$THM_BG_BASE"

THM_ROLE_ACTIVE_BG="$THM_GREEN"
THM_ROLE_ACTIVE_FG="$THM_BG_BASE"
THM_ROLE_INACTIVE_BG="$THM_BG_SURFACE"
THM_ROLE_INACTIVE_FG="$THM_GREEN"
