# Monochrome theme — all modules use gray tones, minimal color distraction
THM_ROLE_SESSION="$THM_GRAY"
THM_ROLE_DIRECTORY="$THM_GRAY"
THM_ROLE_SSH="$THM_GRAY"
THM_ROLE_APP="$THM_GRAY"
THM_ROLE_DATETIME="$THM_GRAY"
THM_ROLE_BATTERY="$THM_GRAY"
THM_ROLE_WEATHER="$THM_GRAY"

THM_ROLE_SESSION_FG="$THM_FG_TEXT"
THM_ROLE_MODULE_FG="$THM_FG_TEXT"

THM_ROLE_ACTIVE_BG="$THM_FG_TEXT"
THM_ROLE_ACTIVE_FG="$THM_BG_BASE"
THM_ROLE_INACTIVE_BG="$THM_BG_SURFACE"
THM_ROLE_INACTIVE_FG="$THM_FG_TEXT"
